# Nombre de la aplicación
spring.application.name=trinomech-backend

# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/trinomech
spring.datasource.username=postgres
spring.datasource.password=abc123

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostrar SQL (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del servidor
server.port=8080
